//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fuzzy
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int Numer { get; set; }
        public Nullable<double> Wynik { get; set; }
        public int uzytkownik { get; set; }
    }
}
